* 1. Resumen
  *- Es un apartado fundamental. Es lo primero que se lee y muchas*
    veces lo único que lee. Es la síntesis de todo el trabajo
    realizado, qué, cómo y por qué hemos hecho el trabajo. Debe ser
    auto contenido y debemos esbozar nuestras conclusiones.*
* 2. Introducción
  *- Enmarca y sitúa el trabajo a realizar.*
  - El trabajo aqui descrito se enmarca como el trabajo de 3 de la
    Asignatura de Proyecto Hardware.  El trabajo en cuestión consiste
    en el desarrollo de una herramienta de ayuda a la resolución del
    popular puzzle sudoku
* 3. Objetivos
  - Explica qué se quiere conseguir.
  - El objetivo principal del proyecto es la creación de un sencillo
    programa de ayuda a la resolución del popular puzzle numérico del
    sudoku.
  - Desde un punto de vista pedagógico existen otros objetivos no
    estrictamente relacionados con el objetivo principal:
    - Aprender a desarrollar codigo para microcontroladores en
      múltiples lenguajes (tanto de alto como de bajo nivel), y
      conocer las tecnicas que existen para la interacción y compilado
      conjunto de un programa realizado en múltiples lenguajes.
    - Comparar a nivel puramente técnico múltiples lenguajes y
      combinaciones de los mismos, principalmente mediante la métrica
      'nº de instrucciones de procesador para terminar una tarea'
* 4. Metodología
  - Describe los pasos realizados para llegar hasta los
    resultados. Todas aquellas decisiones de diseño tomadas en el
    proceso deben incluirse.En la asignatura de Proyecto Hardware se
    debe explicar en este apartado el esquema del proyecto (ficheros y
    funciones que lo componen), número total de líneas de código y
    horas de dedicación. Así cómo el código desarrollado comentado.
* 5. Resultado(s)
  - Hay que presentar los resultados, explicarlos y analizarlos.
* 6. Conclusiones
  - Es lo último que se lee, por tanto es una sección muy importante
    que se debe utilizar para remarcar los mensajes que queremos que
    el lector reciba. Por ejemplo, si estamos evaluando un producto
    podemos enfatizar sus puntos fuertes y sus puntos débiles, y
    señalar posibilidades de mejora. Normalmente al final se incluyen
    referencias, bibliografía, índice de expresiones técnicas y
    anexos.
